package uiAdmin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import kasirapk.connectData;

/**
 *
 * @author muqta
 */
public class ProfileAdmin extends javax.swing.JInternalFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form Profile
     */
    public ProfileAdmin(int userId) {
        initComponents();
        conn = connectData.getConnection();
        loadUserProfile(userId);

    }

    
    private void loadUserProfile(int userId) {
        String sql = "SELECT * FROM tb_user WHERE id_user=?";
        
        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, userId);
            rs = pst.executeQuery();

            if (rs.next()) {
                idUser.setText(rs.getString("id_user"));
                namaUser.setText(rs.getString("nama_user"));
                EmailUser.setText(rs.getString("email_user"));
                roleUser.setText(rs.getString("role"));
                usernameUser.setText(rs.getString("username_user"));
                
                // Mask password for security
                passwordUser.setText("******"); 
            } else {
                JOptionPane.showMessageDialog(null, "Data user tidak ditemukan!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbid = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        idUser = new javax.swing.JLabel();
        Jpannel2 = new javax.swing.JPanel();
        lbNama = new javax.swing.JLabel();
        Jpannel1 = new javax.swing.JPanel();
        namaUser = new javax.swing.JLabel();
        Jpannel3 = new javax.swing.JPanel();
        LbEmail = new javax.swing.JLabel();
        jpannel4 = new javax.swing.JPanel();
        EmailUser = new javax.swing.JLabel();
        jPannel5 = new javax.swing.JPanel();
        lbRole = new javax.swing.JLabel();
        RoleUser = new javax.swing.JPanel();
        roleUser = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbUsername = new javax.swing.JLabel();
        jPannel6 = new javax.swing.JPanel();
        usernameUser = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbPassword = new javax.swing.JLabel();
        jPannel7 = new javax.swing.JPanel();
        passwordUser = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lbid.setBackground(new java.awt.Color(255, 255, 255));

        lbID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbID.setText("ID");

        javax.swing.GroupLayout lbidLayout = new javax.swing.GroupLayout(lbid);
        lbid.setLayout(lbidLayout);
        lbidLayout.setHorizontalGroup(
            lbidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbID)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbidLayout.setVerticalGroup(
            lbidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbidLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbID)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        idUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idUser.setText("Id User");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idUser)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idUser)
                .addContainerGap())
        );

        Jpannel2.setBackground(new java.awt.Color(255, 255, 255));

        lbNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNama.setText("Nama");

        javax.swing.GroupLayout Jpannel2Layout = new javax.swing.GroupLayout(Jpannel2);
        Jpannel2.setLayout(Jpannel2Layout);
        Jpannel2Layout.setHorizontalGroup(
            Jpannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpannel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNama)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Jpannel2Layout.setVerticalGroup(
            Jpannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpannel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNama)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jpannel1.setBackground(new java.awt.Color(255, 255, 255));

        namaUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        namaUser.setText("nama");

        javax.swing.GroupLayout Jpannel1Layout = new javax.swing.GroupLayout(Jpannel1);
        Jpannel1.setLayout(Jpannel1Layout);
        Jpannel1Layout.setHorizontalGroup(
            Jpannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpannel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaUser)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        Jpannel1Layout.setVerticalGroup(
            Jpannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpannel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namaUser)
                .addContainerGap())
        );

        Jpannel3.setBackground(new java.awt.Color(255, 255, 255));

        LbEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LbEmail.setText("Email");

        javax.swing.GroupLayout Jpannel3Layout = new javax.swing.GroupLayout(Jpannel3);
        Jpannel3.setLayout(Jpannel3Layout);
        Jpannel3Layout.setHorizontalGroup(
            Jpannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpannel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbEmail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Jpannel3Layout.setVerticalGroup(
            Jpannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpannel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LbEmail)
                .addContainerGap())
        );

        jpannel4.setBackground(new java.awt.Color(255, 255, 255));

        EmailUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EmailUser.setText("email");

        javax.swing.GroupLayout jpannel4Layout = new javax.swing.GroupLayout(jpannel4);
        jpannel4.setLayout(jpannel4Layout);
        jpannel4Layout.setHorizontalGroup(
            jpannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpannel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmailUser)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jpannel4Layout.setVerticalGroup(
            jpannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpannel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmailUser)
                .addContainerGap())
        );

        jPannel5.setBackground(new java.awt.Color(255, 255, 255));

        lbRole.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbRole.setText("Role");

        javax.swing.GroupLayout jPannel5Layout = new javax.swing.GroupLayout(jPannel5);
        jPannel5.setLayout(jPannel5Layout);
        jPannel5Layout.setHorizontalGroup(
            jPannel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPannel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRole)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPannel5Layout.setVerticalGroup(
            jPannel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPannel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRole)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RoleUser.setBackground(new java.awt.Color(255, 255, 255));

        roleUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        roleUser.setText("role");

        javax.swing.GroupLayout RoleUserLayout = new javax.swing.GroupLayout(RoleUser);
        RoleUser.setLayout(RoleUserLayout);
        RoleUserLayout.setHorizontalGroup(
            RoleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoleUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roleUser)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        RoleUserLayout.setVerticalGroup(
            RoleUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoleUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roleUser)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lbUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbUsername.setText("username");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbUsername)
                .addContainerGap())
        );

        jPannel6.setBackground(new java.awt.Color(255, 255, 255));

        usernameUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameUser.setText("username");

        javax.swing.GroupLayout jPannel6Layout = new javax.swing.GroupLayout(jPannel6);
        jPannel6.setLayout(jPannel6Layout);
        jPannel6Layout.setHorizontalGroup(
            jPannel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPannel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameUser)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPannel6Layout.setVerticalGroup(
            jPannel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPannel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lbPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPassword.setText("Password");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPassword)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPannel7.setBackground(new java.awt.Color(255, 255, 255));

        passwordUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordUser.setText("password");

        javax.swing.GroupLayout jPannel7Layout = new javax.swing.GroupLayout(jPannel7);
        jPannel7.setLayout(jPannel7Layout);
        jPannel7Layout.setHorizontalGroup(
            jPannel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPannel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passwordUser)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPannel7Layout.setVerticalGroup(
            jPannel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPannel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passwordUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpannel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpannel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPannel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jpannel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpannel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPannel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPannel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jpannel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpannel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpannel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jpannel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RoleUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPannel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPannel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPannel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmailUser;
    private javax.swing.JPanel Jpannel1;
    private javax.swing.JPanel Jpannel2;
    private javax.swing.JPanel Jpannel3;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JPanel RoleUser;
    private javax.swing.JLabel idUser;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPannel5;
    private javax.swing.JPanel jPannel6;
    private javax.swing.JPanel jPannel7;
    private javax.swing.JPanel jpannel4;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbRole;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPanel lbid;
    private javax.swing.JLabel namaUser;
    private javax.swing.JLabel passwordUser;
    private javax.swing.JLabel roleUser;
    private javax.swing.JLabel usernameUser;
    // End of variables declaration//GEN-END:variables
}